[project]
name = "fx-vol-regime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "darts>=0.37.1",
    "yfinance>=1.1.0",
]
